name: Deploy

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    if: github.repository == 'ml-stat-Sustech/TorchCP'
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v2
      - run: |
            git fetch --prune --unshallow            

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U poetry
          poetry install          

      - name: Build package
        run: |
          git push
          poetry build          

#      - name: Publish package to PyPI
#        if: github.event.action == 'published'
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          user: __token__
#          password: ${{ secrets.pypi_password }}

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.JIANGUO_TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
